default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/<%= ENV['CYPRESS'] ? 'test' : 'development' %>.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: chordly_production
  username: postgres
  password: postgres
  host: chordly_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
